src/java/backing/beans/CheckLogin.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package backing.beans;

import commonBackingBean.RoleBean;
import entities.Student;
import entities.TeacherAdmin;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpSession;
import sessionBeans.StudentFacadeLocal;
import sessionBeans.TeacherAdminFacadeLocal;
import tools.StaticFields;
import tools.User;
import org.jasypt.util.password.StrongPasswordEncryptor;

/**
 *
 * @author myPC
 */
@Named
@SessionScoped
public class CheckLogin implements Serializable {

    @Inject
    private RoleBean roleBean;
    @EJB
    private StudentFacadeLocal studentFacadeLocal;
    @EJB
    private TeacherAdminFacadeLocal teacherAdminFacadeLocal;

    private User user;
    private String username, password, welcomeMess;
    private String rand;
    private int tryTime = 0;
    private boolean logined = false, rendered = true;
    private final int tryTimeLimitedNumber = 3;
    private int roleType = StaticFields.STUDENT_ROLE;
    private final HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);

    private boolean isUserlegal(String name, String password) {
        boolean result = false;
        if (getRoleType() == StaticFields.STUDENT_ROLE) {
            List<Student> studentsList = studentFacadeLocal.getQueryResultList("select * from student where name='" + name + "'");
            if (null != studentsList && studentsList.size() > 0) {
                result = this.isValidUser(password, studentsList.get(0).getPassword());
                if (result) {
                    session.setAttribute(StaticFields.STUDENTREF, studentsList.get(0));
                }
            }

        } else if (getRoleType() == StaticFields.TEACHER_ROLE || getRoleType() == StaticFields.ADMIN_ROLE) {
            List<TeacherAdmin> teacherAdminList = teacherAdminFacadeLocal.getQueryResultList("select * from TEACHER_ADMIN where name='" + name + "'");
            if (null != teacherAdminList && teacherAdminList.size() > 0) {
                result = this.isValidUser(password, teacherAdminList.get(0).getPassword());
                if (result) {
                    session.setAttribute(StaticFields.TEACHERREF, teacherAdminList.get(0));
                }
            }
        }
        return result;
    }

    public String validateUser() {
//        String genRand = ((String) session.getAttribute("rand")).trim();
        if (!FacesContext.getCurrentInstance().getMessageList().isEmpty()) {
            FacesContext.getCurrentInstance().getMessageList().clear();
        }
        if (tryTime++ < tryTimeLimitedNumber) {//尝试登录未超过规定次数
            //  if (genRand.equals(this.rand)) {//验证码正确
            if (isUserlegal(this.username, this.password)) {//用户存在
                session.setAttribute(StaticFields.LOGIN_ROLE, this.getRoleType());
                session.setAttribute("myUser", this.getUser());
                session.setAttribute("userno", this.username);
                this.welcomeMess = this.getUser().getName();
                tryTime = 0;
                this.logined = true;
                return StaticFields.MAIN_PAGE;
                // return;
            } else {//用户名或密码错误
                FacesContext.getCurrentInstance().addMessage("loginButton", new FacesMessage(StaticFields.MESSAGES_PROPTES.getString("ivalidUP")));
                this.rand = null;
                this.password = null;
                return null;
            }
//            } else {//验证码错误
//                this.rand = null;
//                this.password = null;
//                FacesContext.getCurrentInstance().addMessage("validatorCode", new FacesMessage(StaticFields.MESSAGES_PROPTES.getString("invValiCode")));
//                return null;
//            }
        } else {
            this.rendered = false;
            FacesContext.getCurrentInstance().addMessage("loginButton", new FacesMessage(StaticFields.MESSAGES_PROPTES.getString("tryFaild")));
            this.rand = null;
            this.password = null;
            return null;
        }
    }

    public String submit() {//注册
        //判断是学生还是教师，如果是教师，则选择Teacher表，否则选择Student表
        if (this.getRoleType() == StaticFields.STUDENT_ROLE) {
            Student student = new Student();
            student.setEmail(this.getUser().getEmail());
            student.setFirstname(this.getUser().getFirstName());
            student.setSecondname(this.getUser().getSecondName());
            student.setName(this.getUser().getName());
            student.setPassword(this.encrypt(this.getUser().getPassword()));
            studentFacadeLocal.create(student);
        } else if (this.getRoleType() == StaticFields.TEACHER_ROLE || this.getRoleType() == StaticFields.ADMIN_ROLE) {
            TeacherAdmin teacherAdmin = new TeacherAdmin();
            teacherAdmin.setEmail(this.getUser().getEmail());
            teacherAdmin.setFirstname(this.getUser().getFirstName());
            teacherAdmin.setSecondname(this.getUser().getSecondName());
            teacherAdmin.setName(this.getUser().getName());
            teacherAdmin.setPassword(this.encrypt(this.getUser().getPassword()));
            teacherAdminFacadeLocal.create(teacherAdmin);
        }
        return null;
    }

    public String login(int loginType) {
        this.setRoleType(loginType);
        return StaticFields.LONGIN_PATH;
    }

    public String logout() {
        this.user = null;
        this.username = null;
        this.logined = false;
        this.password = null;
        this.roleType = 0;
        session.invalidate();
        return StaticFields.NOLOGIN_MAIN_PAGE;
    }

    public String register() {
        return StaticFields.REGISTER_PATH;
    }

    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @param rand the rand to set
     */
    public void setRand(String rand) {
        this.rand = rand;
    }

    public String getRand() {
        return this.rand;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return this.password;
    }

    /**
     * @return the welcomeMess
     */
    public String getWelcomeMess() {
        return welcomeMess;
    }

    /**
     * @return the rendered
     */
    public boolean isLogined() {
        return logined;
    }

    /**
     * @param rendered the rendered to set
     */
    public void setLogined(boolean rendered) {
        this.logined = rendered;
    }

    /**
     * @return the rendered
     */
    public boolean isRendered() {
        return rendered;
    }

    /**
     * @param rendered the rendered to set
     */
    public void setRendered(boolean rendered) {
        this.rendered = rendered;
    }

    /**
     * @return the user
     */
    public User getUser() {
        if (null == user) {
            return new User();
        }
        return user;
    }

    /**
     * @return the userType
     */
    public int getUserType() {
        return getRoleType();
    }

    /**
     * @param userType the userType to set
     */
    public void setUserType(int userType) {
        this.setRoleType(userType);
    }

    /**
     * @return the r oleType
     */
    public int getRoleType() {
        return roleType;
    }

    /**
     * @param roleType the roleType to set
     */
    public void setRoleType(int roleType) {
        this.roleType = roleType;
    }

    public String getRoleinfo() {
        return StaticFields.MESSAGES_PROPTES.getString(roleBean.getRoleinfo(this.roleType).getRolename());
    }

    StrongPasswordEncryptor passwordEncryptor = new StrongPasswordEncryptor();

    private boolean isValidUser(String inputPassword, String encryptedPassword) {
        if (passwordEncryptor.checkPassword(inputPassword, encryptedPassword)) {
            return true;
        } else {
            return false;
        }
    }

    private String encrypt(String password) {
        return passwordEncryptor.encryptPassword(password);
        //Then put encryptedPassword into database.
    }
}

src/java/backing/beans/MyMainFrame.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backing.beans;

import entities.Resourceinfo;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import tools.PublicFields;

/**
 *
 * @author asus
 */
@SessionScoped
@Named
public class MyMainFrame implements Serializable {

    @Inject
    PublicFields publicFields;
    @Inject
            CheckLogin checkLogin;
    Resourceinfo resource = new Resourceinfo();
    private String pageName;

    public List<Resourceinfo> getResouceMap() {
        return publicFields.getReslistMap(checkLogin.getRoleType());
    }

    /**
     * @return the pageName
     */
    public String getPageName() {
        if(null==pageName){
            pageName="news";
        }
        return pageName;
    }

    /**
     * @param pageName the pageName to set
     */
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

}

src/java/commonBackingBean/NewsBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commonBackingBean;

import entities.News;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.ResourceBundle;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import operation.student.StuNewsBean;
import operation.teacher.TeaNewsBean;
import tools.StaticFields;

/**
 *
 * @author asus
 */
@Named
@ApplicationScoped
public class NewsBean implements java.io.Serializable{
    @Inject
    private StuNewsBean stuNewsBean;
    @Inject
    private TeaNewsBean teaNewsBean;
    private LinkedHashMap<String, List<News>> newsHashMap;


 
    /**
     * @return the newsHashMap
     */
    
    public LinkedHashMap<String, List<News>> getNewsHashMap() {
        if(null==newsHashMap){
            String[] roleStrings=StaticFields.MESSAGES_PROPTES.getString("roleArray").split(",");
            newsHashMap=new LinkedHashMap<>();
            newsHashMap.put(roleStrings[0], stuNewsBean.getRecentNews());
            newsHashMap.put(roleStrings[1], teaNewsBean.getRecentNews());
        }
        return newsHashMap;
    }

    /**
     * @param newsHashMap the newsHashMap to set
     */
    public void setNewsHashMap(LinkedHashMap<String, List<News>> newsHashMap) {
        this.newsHashMap = newsHashMap;
    }

}

src/java/commonBackingBean/SchoolBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package commonBackingBean;

import entities.School;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import sessionBeans.SchoolFacadeLocal;
import tools.StaticFields;

/**
 *
 * @author myPC
 */
@Named
@SessionScoped
public class SchoolBean implements Serializable {

    @EJB
    private SchoolFacadeLocal schoolFacadeLocal;
    private School school;
    private List<School> schoolList;
    private String schoolId;
    private String schoolName;
    private String pinyin;
    private String mytype;
    private LinkedHashMap<String, Integer> myCateType;

    public String alterSchool(String sId, String sName, String sPinyin) {
        schoolFacadeLocal.executUpdate("update school set name='" + sName + "',pinyin='" + sPinyin + " where id=" + sId);
        return "viewSchools.xhtml";
    }

    public String addSchool() {
        schoolFacadeLocal.executUpdate("insert into school" + " ( name, pinyin) values('" +  schoolName + "', '" + pinyin + "')");
        return "viewSchools.xhtml";
    }

    public LinkedHashMap<String, Integer> getMytypeMap() {
        if (null == myCateType) {
            myCateType = new LinkedHashMap<>();
            myCateType.put(StaticFields.CATE_TYPE[0], 0);
            myCateType.put(StaticFields.CATE_TYPE[1], 1);
            myCateType.put(StaticFields.CATE_TYPE[2], 2);
        }
        return myCateType;
    }

    /**
     * @return the nameofunit
     */
    public School getSchool() {
        return school;
    }

    /**
     * @param schoolPara the nameofunit to set
     */
    public void setSchool(School schoolPara) {
        this.school = schoolPara;
    }

    /**
     * @return the nameofunitList
     */
    public List<School> getNameofunitList() {
        if (schoolList == null) {
            schoolList = schoolFacadeLocal.findAll();
        }
        return schoolList;
    }

    /**
     * @param nameofunitList the nameofunitList to set
     */
    public void setSchoolList(List<School> nameofunitList) {
        this.schoolList = nameofunitList;
    }

    /**
     * @return the schoolId
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * @param schoolId the schoolId to set
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * @return the schoolName
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * @param schoolName the schoolName to set
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * @return the pinyin
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * @param pinyin the pinyin to set
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

       /**
     * @return the mytype
     */
    public String getMytype() {
        return mytype;
    }

    /**
     * @param mytype the mytype to set
     */
    public void setMytype(String mytype) {
        this.mytype = mytype;
    }
}

src/java/operation/student/StuNewsBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package operation.student;

import entities.News;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import sessionBeans.NewsFacadeLocal;
import tools.StaticFields;

@Named
@SessionScoped
public class StuNewsBean implements Serializable {

    @EJB
    NewsFacadeLocal newsFacadeLocal;
    private News news = new News();
    private List<News> recentNews;
    private News directNews;

    public String directToNews() {
        String newsId = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get(StaticFields.REQUEST_NEWS_ID);
        directNews = (News) (newsFacadeLocal.getQueryResultList("select * from news where id=" + newsId).get(0));
        return "news.xhtml";
    }

    /**
     * @return the news
     */
    public News getNews() {
        return news;
    }

    /**
     * @param news the news to set
     */
    public void setNews(News news) {
        this.news = news;
    }

    /**
     * @return the directNews
     */
    public News getDirectNews() {
        return directNews;
    }

    /**
     * @param directNews the directNews to set
     */
    public void setDirectNews(News directNews) {
        this.directNews = directNews;
    }

    /**
     * @return the recentNews
     */
    public List<News> getRecentNews() {
        if (null == recentNews) {
            int begin = (StaticFields.STU_NEWS_COUNT - StaticFields.NUM_NEWS_SHOWN) < 0 ? 0 : (StaticFields.STU_NEWS_COUNT - StaticFields.NUM_NEWS_SHOWN);
            recentNews = newsFacadeLocal.getQueryResultList("select * from news where for_role=" + StaticFields.STUDENT_ROLE + " OFFSET " + begin+ " ROWS");
        }
        return recentNews;
    }

    /**
     * @param recentNews the recentNews to set
     */
    public void setRecentNews(List<News> recentNews) {
        this.recentNews = recentNews;
    }
}

web/operation/addNews.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <body>
     
        <ui:composition template="./../noLogin/myTemplate2.xhtml">
            <ui:define name="content">
                 <h1><h:outputLabel value="#{msgs.add}"/></h1>
                <h:form prependId="false">
                    <h:messages   style="color: red" id="latestMessage"/>
                    <h:panelGrid columns="2">
                        <h:outputLabel value="#{msgs.title}"/>
                        <h:inputText value="#{newsBean.news.newsTitle}"/>
                        <h:outputLabel value="#{msgs.content}"/>
                        <h:inputTextarea value="#{newsBean.news.content}" />
                        <h:commandButton action="#{newsBean.addNews()}" value="#{msgs.save}" />
                    </h:panelGrid>
                    <h:dataTable value="#{newsBean.recentNews}" var="newsItem" border="1" styleClass="tableClass" headerClass="tableHeaderClass" 
                                 columnClasses="firstColumn,secondColum,thirdColumn,fourthColum，fifthColum  " 
                                 >
                        <f:facet name="caption">#{msgs.newsInfo}#{msgs.list}</f:facet>
                        <h:column> 
                            <f:facet name="header">#{msgs.title}</f:facet>
                            <h:outputLabel value="#{newsItem.newsTitle}"/>  
                        </h:column> 
                        <h:column> 
                            <f:facet name="header">#{msgs.content}</f:facet>
                            <h:outputLabel value="#{newsItem.content}"/>  
                        </h:column> 
                        <h:column>
                            <f:facet name="header"></f:facet>
                            <h:commandButton value="#{msgs.delete}" action="#{newsBean.delete(newsItem.id)}"/>
                        </h:column> 
                    
                    </h:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/operation/initKnowledgeFront.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>选择学习进度</title>
    </h:head>
    <h:body>
        <br/>
        <br/>
        <br/>
        <br/>
         <h:form>
            <h:outputLabel value="年级"/>
            <h:selectOneMenu value="#{initKnowledgeFront.major}" >
                <f:selectItems value="#{initKnowledgeFront.majorItems}"/>
                <f:ajax render="subject"/>
            </h:selectOneMenu>
            <h:outputLabel  value="课程" />
            <h:selectOneMenu id="subject" value="#{initKnowledgeFront.subject}">
                <f:selectItems value="#{initKnowledgeFront.subjectItems}"/>
                <f:ajax render="knowledge"/>
            </h:selectOneMenu>
            <h:outputLabel  value="知识点" />
            <h:selectOneMenu id="knowledge" value="#{initKnowledgeFront.knowledge}">
                <f:selectItems value="#{initKnowledgeFront.knowledgeItems}"/>
            </h:selectOneMenu>
           
        </h:form>
    </h:body>
</html>

web/operation/main.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="./../template/mainFrame/mainFrame.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:define name="left">
        <h:form>
            <h:panelGrid columns="1">
                <c:forEach items="#{myMainFrame.resouceMap}" var="myresouce">
                    <h:commandLink value="#{myresouce.name}" action="#{myMainFrame.setPageName(myresouce.valueinfo)}"/>         
                </c:forEach>
            </h:panelGrid>
        </h:form>
    </ui:define>

    <ui:define name="content">
        <ui:include src="#{myMainFrame.pageName}.xhtml"/>
    </ui:define>

</ui:composition>

web/operation/teacherInfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <script type="text/javascript"/>
    <h:head >
    </h:head>
    <body>
        <ui:composition template="./../noLogin/myTemplate2.xhtml">
            <ui:define name="content">
                <div class="companyInfo">
                    <h:form id="myForm">
                        <h:messages  style="color: red" id="latestMessage"/>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="#{msgs.selectSchool}"/>
                            <h:selectOneMenu value="#{nameofUnitBean.schoolId}" id="myschool" required="true"  validator="#{userinfoBean.assingValue2SchoolId}" >
                                <f:selectItem itemLabel="#{msgs.selectSchool}" itemValue="null" />
                                <f:selectItems value="#{nameofUnitBean.schoolMap}"/>
                                <f:ajax render="myschoolId"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                        <c:set value="#{nameofUnitBean.schoolId}" var="schoolId"/>

                        <h:panelGrid   columns="5">
                            <h:outputLabel value="#{msgs.teacherUno}:"  />
                            <h:inputText id="tuno" value="#{userinfoBean.userno}"/>
                            <h:outputLabel value="#{msgs.name}:" />
                            <h:inputText id="tname" value="#{userinfoBean.studentname}"/>
                            <h:commandButton action="#{userinfoBean.addTeacher}" value="#{msgs.add}"/>
                        </h:panelGrid>

                        <h1><h:outputText value="教师信息列表"></h:outputText></h1>
                        <h:dataTable id ="myschoolId" value="#{userinfoBean.teacherList}" var="ci"
                                     border="1" styleClass="tableClass" headerClass="tableHeaderClass" 
                                     columnClasses="firstColumn,secondColum,thirdColumn,fourthColum，fifthColum  " 
                                     >
                            <h:column> 
                                <f:facet name="header">#{msgs.name}</f:facet>
                                <h:outputText value="#{ci.name}"/>  
                            </h:column>  
                            <h:column> 
                                <f:facet name="header">#{msgs.teacherUno}</f:facet>
                                <h:outputText value="#{ci.uno}"/>  
                            </h:column>

                            <h:column>
                                <f:facet name="header">#{msgs.role}</f:facet>
                                <h:selectOneMenu value="#{ci.roleid}" required="true">
                                    <f:selectItem itemLabel="#{ci.roleinfo.name}" itemValue="#{ci.roleid}" />
                                    <f:selectItems value="#{publicFields.roleMap}"/>
                                </h:selectOneMenu>
                            </h:column>


                            <h:column> 
                                <f:facet name="header">#{msgs.school}</f:facet>
                                <h:selectOneMenu value="#{ci.nameofunit.id}" id="myschool" required="true">
                                    <f:selectItem itemLabel="#{ci.nameofunit.name}" itemValue="#{ci.nameofunit.id}" />
                                    <f:selectItems value="#{nameofUnitBean.schoolMap}"/>
                                    <f:ajax render="myschoolId" event="change"/>
                                </h:selectOneMenu>
                            </h:column>
                            <h:column>
                                <f:facet name="header">#{msgs.alter}</f:facet>
                                <h:commandButton value="#{msgs.alter}" action="#{userinfoBean.saveTeacher(ci.uno,ci.roleid,ci.nameofunit.id)}"/>
                            </h:column> 
                            <h:column>
                                <f:facet name="header">#{msgs.delete}</f:facet>
                                <h:commandButton value="#{msgs.delete}" action="#{userinfoBean.deleteTeacher(ci)}"/>
                            </h:column>
                        </h:dataTable>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/operation/viewSchools.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      >
    <body>
    
        <ui:composition template="./../noLogin/myTemplate2.xhtml">
            <ui:define name="content">

                <h1><h:outputLabel value="#{msgs.schools}:#{msgs.pinyin}#{msgs.order}"/></h1>
                <h:messages   style="color: red" id="latestMessage"/>


                <table rendered="#{schoolBean.nameofunitList.size()>0}" border="1">
                    <tr>
                        <th>#{msgs.schoolNum}</th>
                        <th>#{msgs.schoolName}</th>
                        <th>#{msgs.school}#{msgs.pinyin}#{msgs.firstChar}</th>
                        <th>#{msgs.cate}</th>
                        <th>#{msgs.unit}</th>
                        <th>#{msgs.alter}</th>
                        <th>#{msgs.delete}</th>
                    </tr>
                    <c:forEach items="#{schoolBean.nameofunitList}" var="school">
                        <h:form>
                            <tr>
                                <td><h:outputLabel value="#{school.id}"/></td>
                                <td><h:inputText value="#{school.name}"/></td>
                                <td><h:inputText value="#{school.pinyin}" /></td>
                                <td><h:selectOneMenu value="#{school.mytype}">
                                        <f:selectItems  value="#{schoolBean.mytypeMap}"/>
                                    </h:selectOneMenu></td>
                                <td><h:outputLabel value="#{school.parNameofunit.name}"/></td>
                                <td>
                                    <h:commandButton value="#{msgs.alter}" action="#{schoolBean.alterSchool(school.id,school.name,school.pinyin,school.mytype)}" />
                                </td>
                                <td>
                                    <h:commandButton value="#{msgs.delete}" action="#{schoolBean.deleteSchool()}">
                                        <f:param value="#{school.id}" name="schoolId"/>
                                    </h:commandButton>
                                </td>
                            </tr>
                        </h:form>
                    </c:forEach>
                </table>


                <h:form>
                    <h:panelGrid>
                        <h1><h:outputLabel value="#{msgs.addSchool}"/></h1>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="#{msgs.schoolNum}" />
                            <h:inputText value="#{schoolBean.schoolId}" required="true"/>
                            <h:outputLabel value="#{msgs.schoolName}" />
                            <h:inputText value="#{schoolBean.schoolName}" required="true"/>
                            <h:outputLabel value="#{msgs.school}#{msgs.pinyin}#{msgs.firstChar}" />
                            <h:inputText value="#{schoolBean.pinyin}" required="true"/>
                            <h:outputLabel value="#{msgs.cate}" />
                            <h:selectOneMenu value="#{schoolBean.mytype}">
                                <f:selectItems  value="#{schoolBean.mytypeMap}"/>
                            </h:selectOneMenu>
                            <h:commandButton action="#{schoolBean.addSchool()}" value="#{msgs.add}"/>
                        </h:panelGrid>
                    </h:panelGrid>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>